// AUTO-GENERATED from /workspace/_app-specs/homeowners-application/
// (fields.json + Homeowners_Insurance_Application.pdf, Josh 2026-07-22).
// 281 fields, 7 sections, exact PDF AcroForm names and order. Do not hand-edit.

export interface HAField {
  name: string;
  label: string;
  type: "text" | "checkbox";
  maxlen?: number;
}

export type HAItem =
  | { kind: "field"; field: HAField }
  | { kind: "yesno"; question: string; yes: HAField; no: HAField }
  | { kind: "losstable"; columns: string[]; rows: HAField[][] }
  | { kind: "prose"; text: string };

export interface HAGroup {
  heading: string | null;
  items: HAItem[];
}

export interface HASection {
  number: number;
  title: string;
  intro: string;
  groups: HAGroup[];
}

export const HOMEOWNERS_APPLICATION: HASection[] = [
  {
    number: 1,
    title: "Applicant and Policy Information",
    intro: "Please provide legal names exactly as they should appear on the policy.",
    groups: [
      {
        heading: "APPLICANT INFORMATION",
        items: [
          { kind: "field", field: { name: "primary_applicant_-_full_legal_name_1", label: "Primary Applicant - Full Legal Name", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "date_of_birth_2", label: "Date of Birth", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "marital_status_3", label: "Marital Status", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "co-applicant_-_full_legal_name_4", label: "Co-Applicant - Full Legal Name", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "date_of_birth_5", label: "Date of Birth", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "marital_status_6", label: "Marital Status", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "primary_phone_7", label: "Primary Phone", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "alternate_phone_8", label: "Alternate Phone", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "email_address_9", label: "Email Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "current_mailing_address_10", label: "Current Mailing Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "city_11", label: "City", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_12", label: "State", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "zip_13", label: "ZIP", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "EMPLOYMENT AND IDENTITY",
        items: [
          { kind: "field", field: { name: "applicant_occupation_14", label: "Applicant Occupation", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "employer_15", label: "Employer", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "years_employed_16", label: "Years Employed", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "co-applicant_occupation_17", label: "Co-Applicant Occupation", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "employer_18", label: "Employer", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "years_employed_19", label: "Years Employed", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "applicant_driver_license_number_20", label: "Applicant Driver License Number", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_21", label: "State", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "co-applicant_driver_license_number_22", label: "Co-Applicant Driver License Number", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_23", label: "State", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "POLICY REQUEST",
        items: [
          { kind: "field", field: { name: "requested_effective_date_24", label: "Requested Effective Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "current_carrier_25", label: "Current Carrier", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "current_policy_number_26", label: "Current Policy Number", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "current_annual_premium_27", label: "Current Annual Premium", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "years_with_current_carrier_28", label: "Years With Current Carrier", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "expiration_date_29", label: "Expiration Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "reason_for_shopping_30", label: "Reason for Shopping", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "CONTACT AND DOCUMENT PREFERENCES",
        items: [
          { kind: "field", field: { name: "email_documents_31", label: "Email documents", type: "checkbox" } },
          { kind: "field", field: { name: "mail_documents_32", label: "Mail documents", type: "checkbox" } },
          { kind: "field", field: { name: "text_notifications_33", label: "Text notifications", type: "checkbox" } },
          { kind: "field", field: { name: "electronic_signature_34", label: "Electronic signature", type: "checkbox" } },
          { kind: "field", field: { name: "additional_named_insureds_or_household_contacts_35", label: "Additional named insureds or household contacts", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 2,
    title: "Property, Occupancy, and Ownership",
    intro: "Complete this section for the residence to be insured.",
    groups: [
      {
        heading: "PROPERTY ADDRESS AND OWNERSHIP",
        items: [
          { kind: "field", field: { name: "property_street_address_36", label: "Property Street Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "city_37", label: "City", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_38", label: "State", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "zip_39", label: "ZIP", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "county_40", label: "County", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "purchase_date_41", label: "Purchase Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "purchase_price_42", label: "Purchase Price", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "estimated_market_value_43", label: "Estimated Market Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "named_owner(s)_on_deed_44", label: "Named Owner(s) on Deed", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "entity___trust_name,_if_any_45", label: "Entity / Trust Name, if any", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "OCCUPANCY",
        items: [
          { kind: "field", field: { name: "primary_residence_46", label: "Primary residence", type: "checkbox" } },
          { kind: "field", field: { name: "secondary_residence_47", label: "Secondary residence", type: "checkbox" } },
          { kind: "field", field: { name: "seasonal_residence_48", label: "Seasonal residence", type: "checkbox" } },
          { kind: "field", field: { name: "tenant_occupied_49", label: "Tenant occupied", type: "checkbox" } },
          { kind: "field", field: { name: "vacant_50", label: "Vacant", type: "checkbox" } },
          { kind: "field", field: { name: "under_renovation_51", label: "Under renovation", type: "checkbox" } },
          { kind: "field", field: { name: "new_purchase_52", label: "New purchase", type: "checkbox" } },
          { kind: "field", field: { name: "existing_residence_53", label: "Existing residence", type: "checkbox" } },
          { kind: "field", field: { name: "short-term_rental_54", label: "Short-term rental", type: "checkbox" } },
          { kind: "field", field: { name: "date_occupied___expected_occupancy_55", label: "Date Occupied / Expected Occupancy", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "number_of_families_56", label: "Number of Families", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "number_of_residents_57", label: "Number of Residents", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "months_occupied_per_year_58", label: "Months Occupied Per Year", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "adults_in_household_59", label: "Adults in Household", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "children_in_household_60", label: "Children in Household", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "unrelated_residents_61", label: "Unrelated Residents", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "domestic_employees_62", label: "Domestic Employees", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "USAGE AND BUSINESS ACTIVITY",
        items: [
          {
            kind: "yesno",
            question: "Home-based business conducted on premises?",
            yes: { name: "yes_63", label: "Yes", type: "checkbox" },
            no: { name: "no_64", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any customers or employees visit the premises?",
            yes: { name: "yes_65", label: "Yes", type: "checkbox" },
            no: { name: "no_66", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any room, unit, or structure rented to others?",
            yes: { name: "yes_67", label: "Yes", type: "checkbox" },
            no: { name: "no_68", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any short-term rental activity (Airbnb/VRBO)?",
            yes: { name: "yes_69", label: "Yes", type: "checkbox" },
            no: { name: "no_70", label: "No", type: "checkbox" },
          },
          { kind: "field", field: { name: "describe_any_business,_rental,_or_unusual_occupancy_exposure_71", label: "Describe any business, rental, or unusual occupancy exposure", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "PRIOR ADDRESS",
        items: [
          { kind: "field", field: { name: "prior_address_72", label: "Prior Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "city_73", label: "City", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_74", label: "State", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "zip_75", label: "ZIP", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "years_at_prior_address_76", label: "Years at Prior Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "prior_residence_type_77", label: "Prior Residence Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "prior_insurance_carrier_78", label: "Prior Insurance Carrier", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 3,
    title: "Dwelling Construction and Building Details",
    intro: "Use best available information; inspection reports may be attached.",
    groups: [
      {
        heading: "CORE DWELLING CHARACTERISTICS",
        items: [
          { kind: "field", field: { name: "year_built_79", label: "Year Built", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "total_living_area_sq._ft._80", label: "Total Living Area Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "number_of_stories_81", label: "Number of Stories", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "number_of_units_82", label: "Number of Units", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "construction_type_83", label: "Construction Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "exterior_wall_material_84", label: "Exterior Wall Material", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "foundation_type_85", label: "Foundation Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_shape_86", label: "Roof Shape", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_material_87", label: "Roof Material", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_year___age_88", label: "Roof Year / Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_condition_89", label: "Roof Condition", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_replacement_cost_90", label: "Roof Replacement Cost", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "roof_permit_date_91", label: "Roof Permit Date", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "INTERIOR AND ATTACHED STRUCTURES",
        items: [
          { kind: "field", field: { name: "bedrooms_92", label: "Bedrooms", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "bathrooms_93", label: "Bathrooms", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "garage_spaces_94", label: "Garage Spaces", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "garage_type_95", label: "Garage Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "basement_sq._ft._96", label: "Basement Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "finished_basement_sq._ft._97", label: "Finished Basement Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "porch___deck_sq._ft._98", label: "Porch / Deck Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "carport_sq._ft._99", label: "Carport Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "other_attached_area_100", label: "Other Attached Area", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "flooring_type(s)_101", label: "Flooring Type(s)", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "kitchen_quality_102", label: "Kitchen Quality", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "bathroom_quality_103", label: "Bathroom Quality", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "custom_features_104", label: "Custom Features", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "DETACHED STRUCTURES",
        items: [
          { kind: "field", field: { name: "detached_garage___shop_sq._ft._105", label: "Detached Garage / Shop Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "guest_house_sq._ft._106", label: "Guest House Sq. Ft.", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "other_structure_type_107", label: "Other Structure Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "fence_type___length_108", label: "Fence Type / Length", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "solar_panels_-_owned_or_leased_109", label: "Solar Panels - Owned or Leased", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "other_structure_value_110", label: "Other Structure Value", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "SPECIAL CONSTRUCTION FEATURES",
        items: [
          { kind: "field", field: { name: "historic_home_111", label: "Historic home", type: "checkbox" } },
          { kind: "field", field: { name: "log_home_112", label: "Log home", type: "checkbox" } },
          { kind: "field", field: { name: "manufactured_home_113", label: "Manufactured home", type: "checkbox" } },
          { kind: "field", field: { name: "modular_home_114", label: "Modular home", type: "checkbox" } },
          { kind: "field", field: { name: "earth-sheltered_115", label: "Earth-sheltered", type: "checkbox" } },
          { kind: "field", field: { name: "eifs_/_synthetic_stucco_116", label: "EIFS / synthetic stucco", type: "checkbox" } },
          { kind: "field", field: { name: "flat_roof_117", label: "Flat roof", type: "checkbox" } },
          { kind: "field", field: { name: "wood_shake_roof_118", label: "Wood shake roof", type: "checkbox" } },
          { kind: "field", field: { name: "unreinforced_masonry_119", label: "Unreinforced masonry", type: "checkbox" } },
          { kind: "field", field: { name: "describe_additions,_renovations,_custom_construction,_or_detached_structures_120", label: "Describe additions, renovations, custom construction, or detached structures", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 4,
    title: "Utilities, Systems, Protection, and Updates",
    intro: "Provide the year of the most recent complete update when known.",
    groups: [
      {
        heading: "ELECTRICAL, PLUMBING, HEATING, AND COOLING",
        items: [
          { kind: "field", field: { name: "electrical_service_amps_121", label: "Electrical Service Amps", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "wiring_type_122", label: "Wiring Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "electrical_update_year_123", label: "Electrical Update Year", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "generator_type___size_124", label: "Generator Type / Size", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "plumbing_type_125", label: "Plumbing Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "plumbing_update_year_126", label: "Plumbing Update Year", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "water_heater_type___age_127", label: "Water Heater Type / Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "sewer___septic_128", label: "Sewer / Septic", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "primary_heat_type_129", label: "Primary Heat Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "heating_update_year_130", label: "Heating Update Year", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "central_ac_type___age_131", label: "Central AC Type / Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "secondary_heat_source_132", label: "Secondary Heat Source", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "WATER AND FUEL SOURCES",
        items: [
          { kind: "field", field: { name: "public___private_water_133", label: "Public / Private Water", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "well_depth___age_134", label: "Well Depth / Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "public_sewer___septic_age_135", label: "Public Sewer / Septic Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "fuel_tank_location___size_136", label: "Fuel Tank Location / Size", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "gas_provider_137", label: "Gas Provider", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "propane_provider_138", label: "Propane Provider", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "oil_tank_age_139", label: "Oil Tank Age", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "water_shutoff_device_140", label: "Water Shutoff Device", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "FIRE AND SECURITY PROTECTION",
        items: [
          { kind: "field", field: { name: "central_station_burglar_alarm_141", label: "Central station burglar alarm", type: "checkbox" } },
          { kind: "field", field: { name: "central_station_fire_alarm_142", label: "Central station fire alarm", type: "checkbox" } },
          { kind: "field", field: { name: "local_alarm_only_143", label: "Local alarm only", type: "checkbox" } },
          { kind: "field", field: { name: "smoke_detectors_144", label: "Smoke detectors", type: "checkbox" } },
          { kind: "field", field: { name: "carbon_monoxide_detectors_145", label: "Carbon monoxide detectors", type: "checkbox" } },
          { kind: "field", field: { name: "fire_extinguishers_146", label: "Fire extinguishers", type: "checkbox" } },
          { kind: "field", field: { name: "sprinkler_system_147", label: "Sprinkler system", type: "checkbox" } },
          { kind: "field", field: { name: "deadbolt_locks_148", label: "Deadbolt locks", type: "checkbox" } },
          { kind: "field", field: { name: "gated_community_149", label: "Gated community", type: "checkbox" } },
          { kind: "field", field: { name: "security_cameras_150", label: "Security cameras", type: "checkbox" } },
          { kind: "field", field: { name: "leak_detection_151", label: "Leak detection", type: "checkbox" } },
          { kind: "field", field: { name: "distance_to_fire_hydrant_152", label: "Distance to Fire Hydrant", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "distance_to_fire_station_153", label: "Distance to Fire Station", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "fire_department_type_154", label: "Fire Department Type", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "SYSTEM CONDITION QUESTIONS",
        items: [
          {
            kind: "yesno",
            question: "Any knob-and-tube, aluminum, or cloth wiring?",
            yes: { name: "yes_155", label: "Yes", type: "checkbox" },
            no: { name: "no_156", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any polybutylene, galvanized, or lead plumbing?",
            yes: { name: "yes_157", label: "Yes", type: "checkbox" },
            no: { name: "no_158", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any active leaks, unrepaired damage, or maintenance issues?",
            yes: { name: "yes_159", label: "Yes", type: "checkbox" },
            no: { name: "no_160", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any open permits or code violations?",
            yes: { name: "yes_161", label: "Yes", type: "checkbox" },
            no: { name: "no_162", label: "No", type: "checkbox" },
          },
          { kind: "field", field: { name: "explain_any_yes_answers_and_list_completed_updates_with_dates_163", label: "Explain any yes answers and list completed updates with dates", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 5,
    title: "Premises Liability and Underwriting Exposures",
    intro: "Answer for the residence, yard, structures, and all household members.",
    groups: [
      {
        heading: "ANIMALS",
        items: [
          { kind: "field", field: { name: "number_of_dogs_164", label: "Number of Dogs", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "breed(s)_165", label: "Breed(s)", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "number_of_other_animals_166", label: "Number of Other Animals", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "animal_type(s)_167", label: "Animal Type(s)", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "any_bite_or_attack_history?_168", label: "Any Bite or Attack History?", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "date___details_169", label: "Date / Details", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "livestock___farm_animals?_170", label: "Livestock / Farm Animals?", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "POOL, SPA, RECREATIONAL, AND PROPERTY FEATURES",
        items: [
          { kind: "field", field: { name: "swimming_pool_171", label: "Swimming pool", type: "checkbox" } },
          { kind: "field", field: { name: "spa_/_hot_tub_172", label: "Spa / hot tub", type: "checkbox" } },
          { kind: "field", field: { name: "diving_board_173", label: "Diving board", type: "checkbox" } },
          { kind: "field", field: { name: "slide_174", label: "Slide", type: "checkbox" } },
          { kind: "field", field: { name: "pool_fenced_175", label: "Pool fenced", type: "checkbox" } },
          { kind: "field", field: { name: "trampoline_176", label: "Trampoline", type: "checkbox" } },
          { kind: "field", field: { name: "treehouse_177", label: "Treehouse", type: "checkbox" } },
          { kind: "field", field: { name: "play_structure_178", label: "Play structure", type: "checkbox" } },
          { kind: "field", field: { name: "zip_line_179", label: "Zip line", type: "checkbox" } },
          { kind: "field", field: { name: "skate_ramp_180", label: "Skate ramp", type: "checkbox" } },
          { kind: "field", field: { name: "pond_/_lake_181", label: "Pond / lake", type: "checkbox" } },
          { kind: "field", field: { name: "dock_182", label: "Dock", type: "checkbox" } },
          { kind: "field", field: { name: "boat_lift_183", label: "Boat lift", type: "checkbox" } },
          { kind: "field", field: { name: "atv_/_dirt_bike_use_184", label: "ATV / dirt bike use", type: "checkbox" } },
          { kind: "field", field: { name: "shooting_range_185", label: "Shooting range", type: "checkbox" } },
          { kind: "field", field: { name: "pool_type___year_186", label: "Pool Type / Year", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "fence_height___gate_type_187", label: "Fence Height / Gate Type", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "water_feature_details_188", label: "Water Feature Details", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "HOUSEHOLD AND PREMISES EXPOSURES",
        items: [
          {
            kind: "yesno",
            question: "Any firearms kept on premises?",
            yes: { name: "yes_189", label: "Yes", type: "checkbox" },
            no: { name: "no_190", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any wood stove, fireplace, or solid-fuel appliance?",
            yes: { name: "yes_191", label: "Yes", type: "checkbox" },
            no: { name: "no_192", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any unusually steep terrain, retaining wall, or cliff exposure?",
            yes: { name: "yes_193", label: "Yes", type: "checkbox" },
            no: { name: "no_194", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any prior foreclosure, bankruptcy, or insurance cancellation?",
            yes: { name: "yes_195", label: "Yes", type: "checkbox" },
            no: { name: "no_196", label: "No", type: "checkbox" },
          },
          {
            kind: "yesno",
            question: "Any resident with a felony conviction or fraud-related offense?",
            yes: { name: "yes_197", label: "Yes", type: "checkbox" },
            no: { name: "no_198", label: "No", type: "checkbox" },
          },
          { kind: "field", field: { name: "explain_any_yes_answers,_including_safeguards_and_dates_199", label: "Explain any yes answers, including safeguards and dates", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "VEHICLES AND STORAGE",
        items: [
          { kind: "field", field: { name: "number_of_vehicles_garaged_200", label: "Number of Vehicles Garaged", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "rv___boat_stored_on_site_201", label: "RV / Boat Stored On Site", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "commercial_vehicle_use_202", label: "Commercial Vehicle Use", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 6,
    title: "Coverage Selection and Valuation",
    intro: "Final limits are subject to replacement-cost estimation and carrier approval.",
    groups: [
      {
        heading: "REQUESTED PROPERTY AND LIABILITY LIMITS",
        items: [
          { kind: "field", field: { name: "coverage_a_-_dwelling_203", label: "Coverage A - Dwelling", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "coverage_b_-_other_structures_204", label: "Coverage B - Other Structures", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "coverage_c_-_personal_property_205", label: "Coverage C - Personal Property", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "coverage_d_-_loss_of_use_206", label: "Coverage D - Loss of Use", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "coverage_e_-_personal_liability_207", label: "Coverage E - Personal Liability", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "coverage_f_-_medical_payments_208", label: "Coverage F - Medical Payments", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "all_other_perils_deductible_209", label: "All Other Perils Deductible", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "wind___hail_deductible_210", label: "Wind / Hail Deductible", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "named_storm_deductible_211", label: "Named Storm Deductible", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "COVERAGE OPTIONS",
        items: [
          { kind: "field", field: { name: "replacement_cost_on_contents_212", label: "Replacement cost on contents", type: "checkbox" } },
          { kind: "field", field: { name: "extended_dwelling_replacement_213", label: "Extended dwelling replacement", type: "checkbox" } },
          { kind: "field", field: { name: "guaranteed_replacement_cost_214", label: "Guaranteed replacement cost", type: "checkbox" } },
          { kind: "field", field: { name: "water_backup_215", label: "Water backup", type: "checkbox" } },
          { kind: "field", field: { name: "service_line_216", label: "Service line", type: "checkbox" } },
          { kind: "field", field: { name: "equipment_breakdown_217", label: "Equipment breakdown", type: "checkbox" } },
          { kind: "field", field: { name: "ordinance_or_law_218", label: "Ordinance or law", type: "checkbox" } },
          { kind: "field", field: { name: "identity_theft_219", label: "Identity theft", type: "checkbox" } },
          { kind: "field", field: { name: "home_systems_220", label: "Home systems", type: "checkbox" } },
          { kind: "field", field: { name: "scheduled_property_221", label: "Scheduled property", type: "checkbox" } },
          { kind: "field", field: { name: "home_cyber_222", label: "Home cyber", type: "checkbox" } },
          { kind: "field", field: { name: "earthquake_223", label: "Earthquake", type: "checkbox" } },
          { kind: "field", field: { name: "flood_quote_requested_224", label: "Flood quote requested", type: "checkbox" } },
          { kind: "field", field: { name: "personal_injury_225", label: "Personal injury", type: "checkbox" } },
          { kind: "field", field: { name: "umbrella_quote_226", label: "Umbrella quote", type: "checkbox" } },
        ],
      },
      {
        heading: "SCHEDULED PROPERTY AND SPECIAL LIMITS",
        items: [
          { kind: "field", field: { name: "jewelry_estimated_value_227", label: "Jewelry Estimated Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "fine_arts_value_228", label: "Fine Arts Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "firearms_value_229", label: "Firearms Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "collectibles_value_230", label: "Collectibles Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "musical_instruments_value_231", label: "Musical Instruments Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "other_scheduled_property_232", label: "Other Scheduled Property", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "list_high-value_items,_appraisals,_and_requested_scheduled_limits_233", label: "List high-value items, appraisals, and requested scheduled limits", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "REPLACEMENT COST INFORMATION",
        items: [
          { kind: "field", field: { name: "estimated_dwelling_replacement_cost_234", label: "Estimated Dwelling Replacement Cost", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "source___estimator_235", label: "Source / Estimator", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "estimate_date_236", label: "Estimate Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "estimated_personal_property_value_237", label: "Estimated Personal Property Value", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "estimated_additional_living_expense_need_238", label: "Estimated Additional Living Expense Need", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
  {
    number: 7,
    title: "Loss History, Mortgagee, Remarks, and Authorization",
    intro: "Report all property and liability losses for all locations during the past five years.",
    groups: [
      {
        heading: "LOSS HISTORY",
        items: [
          {
            kind: "losstable",
            columns: ["Date", "Location", "Type / Cause", "Amount Paid", "Status", "Claim Number"],
            rows: [
              [
                { name: "loss_0_Date_239", label: "Date", type: "text", maxlen: 100 },
                { name: "loss_0_Location_240", label: "Location", type: "text", maxlen: 100 },
                { name: "loss_0_Type / Cause_241", label: "Type / Cause", type: "text", maxlen: 100 },
                { name: "loss_0_Amount Paid_242", label: "Amount Paid", type: "text", maxlen: 100 },
                { name: "loss_0_Status_243", label: "Status", type: "text", maxlen: 100 },
                { name: "loss_0_Claim Number_244", label: "Claim Number", type: "text", maxlen: 100 },
              ],
              [
                { name: "loss_1_Date_245", label: "Date", type: "text", maxlen: 100 },
                { name: "loss_1_Location_246", label: "Location", type: "text", maxlen: 100 },
                { name: "loss_1_Type / Cause_247", label: "Type / Cause", type: "text", maxlen: 100 },
                { name: "loss_1_Amount Paid_248", label: "Amount Paid", type: "text", maxlen: 100 },
                { name: "loss_1_Status_249", label: "Status", type: "text", maxlen: 100 },
                { name: "loss_1_Claim Number_250", label: "Claim Number", type: "text", maxlen: 100 },
              ],
              [
                { name: "loss_2_Date_251", label: "Date", type: "text", maxlen: 100 },
                { name: "loss_2_Location_252", label: "Location", type: "text", maxlen: 100 },
                { name: "loss_2_Type / Cause_253", label: "Type / Cause", type: "text", maxlen: 100 },
                { name: "loss_2_Amount Paid_254", label: "Amount Paid", type: "text", maxlen: 100 },
                { name: "loss_2_Status_255", label: "Status", type: "text", maxlen: 100 },
                { name: "loss_2_Claim Number_256", label: "Claim Number", type: "text", maxlen: 100 },
              ],
              [
                { name: "loss_3_Date_257", label: "Date", type: "text", maxlen: 100 },
                { name: "loss_3_Location_258", label: "Location", type: "text", maxlen: 100 },
                { name: "loss_3_Type / Cause_259", label: "Type / Cause", type: "text", maxlen: 100 },
                { name: "loss_3_Amount Paid_260", label: "Amount Paid", type: "text", maxlen: 100 },
                { name: "loss_3_Status_261", label: "Status", type: "text", maxlen: 100 },
                { name: "loss_3_Claim Number_262", label: "Claim Number", type: "text", maxlen: 100 },
              ],
            ],
          },
        ],
      },
      {
        heading: "MORTGAGEE / ADDITIONAL INTEREST",
        items: [
          { kind: "field", field: { name: "mortgage_company___lender_263", label: "Mortgage Company / Lender", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "loan_number_264", label: "Loan Number", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "mortgagee_mailing_address_265", label: "Mortgagee Mailing Address", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "city_266", label: "City", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "state_267", label: "State", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "zip_268", label: "ZIP", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "second_mortgage___heloc_lender_269", label: "Second Mortgage / HELOC Lender", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "loan_number_270", label: "Loan Number", type: "text", maxlen: 100 } },
        ],
      },
      {
        heading: "PRODUCER REMARKS AND ATTACHMENTS",
        items: [
          { kind: "field", field: { name: "additional_underwriting_remarks_271", label: "Additional underwriting remarks", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "prior_declarations_attached_272", label: "Prior declarations attached", type: "checkbox" } },
          { kind: "field", field: { name: "loss_runs_attached_273", label: "Loss runs attached", type: "checkbox" } },
          { kind: "field", field: { name: "inspection_attached_274", label: "Inspection attached", type: "checkbox" } },
          { kind: "field", field: { name: "photos_attached_275", label: "Photos attached", type: "checkbox" } },
        ],
      },
      {
        heading: "APPLICANT AUTHORIZATION",
        items: [
          { kind: "prose", text: "I certify that the information in this application is true and complete to the best of my knowledge. I understand that material misrepresentation or omission may affect eligibility, coverage, or claims. I authorize the insurer and its representatives to obtain insurance scores, loss history, inspection data, and other underwriting information as permitted by law. This application does not bind coverage." },
          { kind: "field", field: { name: "applicant_signature_276", label: "Applicant Signature", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "date_277", label: "Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "producer___agency_278", label: "Producer / Agency", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "co-applicant_signature_279", label: "Co-Applicant Signature", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "date_280", label: "Date", type: "text", maxlen: 100 } },
          { kind: "field", field: { name: "producer_phone_281", label: "Producer Phone", type: "text", maxlen: 100 } },
        ],
      },
    ],
  },
];

/** All 281 field names, in exact PDF order. */
export const HA_FIELD_NAMES: string[] = [
  "primary_applicant_-_full_legal_name_1",
  "date_of_birth_2",
  "marital_status_3",
  "co-applicant_-_full_legal_name_4",
  "date_of_birth_5",
  "marital_status_6",
  "primary_phone_7",
  "alternate_phone_8",
  "email_address_9",
  "current_mailing_address_10",
  "city_11",
  "state_12",
  "zip_13",
  "applicant_occupation_14",
  "employer_15",
  "years_employed_16",
  "co-applicant_occupation_17",
  "employer_18",
  "years_employed_19",
  "applicant_driver_license_number_20",
  "state_21",
  "co-applicant_driver_license_number_22",
  "state_23",
  "requested_effective_date_24",
  "current_carrier_25",
  "current_policy_number_26",
  "current_annual_premium_27",
  "years_with_current_carrier_28",
  "expiration_date_29",
  "reason_for_shopping_30",
  "email_documents_31",
  "mail_documents_32",
  "text_notifications_33",
  "electronic_signature_34",
  "additional_named_insureds_or_household_contacts_35",
  "property_street_address_36",
  "city_37",
  "state_38",
  "zip_39",
  "county_40",
  "purchase_date_41",
  "purchase_price_42",
  "estimated_market_value_43",
  "named_owner(s)_on_deed_44",
  "entity___trust_name,_if_any_45",
  "primary_residence_46",
  "secondary_residence_47",
  "seasonal_residence_48",
  "tenant_occupied_49",
  "vacant_50",
  "under_renovation_51",
  "new_purchase_52",
  "existing_residence_53",
  "short-term_rental_54",
  "date_occupied___expected_occupancy_55",
  "number_of_families_56",
  "number_of_residents_57",
  "months_occupied_per_year_58",
  "adults_in_household_59",
  "children_in_household_60",
  "unrelated_residents_61",
  "domestic_employees_62",
  "yes_63",
  "no_64",
  "yes_65",
  "no_66",
  "yes_67",
  "no_68",
  "yes_69",
  "no_70",
  "describe_any_business,_rental,_or_unusual_occupancy_exposure_71",
  "prior_address_72",
  "city_73",
  "state_74",
  "zip_75",
  "years_at_prior_address_76",
  "prior_residence_type_77",
  "prior_insurance_carrier_78",
  "year_built_79",
  "total_living_area_sq._ft._80",
  "number_of_stories_81",
  "number_of_units_82",
  "construction_type_83",
  "exterior_wall_material_84",
  "foundation_type_85",
  "roof_shape_86",
  "roof_material_87",
  "roof_year___age_88",
  "roof_condition_89",
  "roof_replacement_cost_90",
  "roof_permit_date_91",
  "bedrooms_92",
  "bathrooms_93",
  "garage_spaces_94",
  "garage_type_95",
  "basement_sq._ft._96",
  "finished_basement_sq._ft._97",
  "porch___deck_sq._ft._98",
  "carport_sq._ft._99",
  "other_attached_area_100",
  "flooring_type(s)_101",
  "kitchen_quality_102",
  "bathroom_quality_103",
  "custom_features_104",
  "detached_garage___shop_sq._ft._105",
  "guest_house_sq._ft._106",
  "other_structure_type_107",
  "fence_type___length_108",
  "solar_panels_-_owned_or_leased_109",
  "other_structure_value_110",
  "historic_home_111",
  "log_home_112",
  "manufactured_home_113",
  "modular_home_114",
  "earth-sheltered_115",
  "eifs_/_synthetic_stucco_116",
  "flat_roof_117",
  "wood_shake_roof_118",
  "unreinforced_masonry_119",
  "describe_additions,_renovations,_custom_construction,_or_detached_structures_120",
  "electrical_service_amps_121",
  "wiring_type_122",
  "electrical_update_year_123",
  "generator_type___size_124",
  "plumbing_type_125",
  "plumbing_update_year_126",
  "water_heater_type___age_127",
  "sewer___septic_128",
  "primary_heat_type_129",
  "heating_update_year_130",
  "central_ac_type___age_131",
  "secondary_heat_source_132",
  "public___private_water_133",
  "well_depth___age_134",
  "public_sewer___septic_age_135",
  "fuel_tank_location___size_136",
  "gas_provider_137",
  "propane_provider_138",
  "oil_tank_age_139",
  "water_shutoff_device_140",
  "central_station_burglar_alarm_141",
  "central_station_fire_alarm_142",
  "local_alarm_only_143",
  "smoke_detectors_144",
  "carbon_monoxide_detectors_145",
  "fire_extinguishers_146",
  "sprinkler_system_147",
  "deadbolt_locks_148",
  "gated_community_149",
  "security_cameras_150",
  "leak_detection_151",
  "distance_to_fire_hydrant_152",
  "distance_to_fire_station_153",
  "fire_department_type_154",
  "yes_155",
  "no_156",
  "yes_157",
  "no_158",
  "yes_159",
  "no_160",
  "yes_161",
  "no_162",
  "explain_any_yes_answers_and_list_completed_updates_with_dates_163",
  "number_of_dogs_164",
  "breed(s)_165",
  "number_of_other_animals_166",
  "animal_type(s)_167",
  "any_bite_or_attack_history?_168",
  "date___details_169",
  "livestock___farm_animals?_170",
  "swimming_pool_171",
  "spa_/_hot_tub_172",
  "diving_board_173",
  "slide_174",
  "pool_fenced_175",
  "trampoline_176",
  "treehouse_177",
  "play_structure_178",
  "zip_line_179",
  "skate_ramp_180",
  "pond_/_lake_181",
  "dock_182",
  "boat_lift_183",
  "atv_/_dirt_bike_use_184",
  "shooting_range_185",
  "pool_type___year_186",
  "fence_height___gate_type_187",
  "water_feature_details_188",
  "yes_189",
  "no_190",
  "yes_191",
  "no_192",
  "yes_193",
  "no_194",
  "yes_195",
  "no_196",
  "yes_197",
  "no_198",
  "explain_any_yes_answers,_including_safeguards_and_dates_199",
  "number_of_vehicles_garaged_200",
  "rv___boat_stored_on_site_201",
  "commercial_vehicle_use_202",
  "coverage_a_-_dwelling_203",
  "coverage_b_-_other_structures_204",
  "coverage_c_-_personal_property_205",
  "coverage_d_-_loss_of_use_206",
  "coverage_e_-_personal_liability_207",
  "coverage_f_-_medical_payments_208",
  "all_other_perils_deductible_209",
  "wind___hail_deductible_210",
  "named_storm_deductible_211",
  "replacement_cost_on_contents_212",
  "extended_dwelling_replacement_213",
  "guaranteed_replacement_cost_214",
  "water_backup_215",
  "service_line_216",
  "equipment_breakdown_217",
  "ordinance_or_law_218",
  "identity_theft_219",
  "home_systems_220",
  "scheduled_property_221",
  "home_cyber_222",
  "earthquake_223",
  "flood_quote_requested_224",
  "personal_injury_225",
  "umbrella_quote_226",
  "jewelry_estimated_value_227",
  "fine_arts_value_228",
  "firearms_value_229",
  "collectibles_value_230",
  "musical_instruments_value_231",
  "other_scheduled_property_232",
  "list_high-value_items,_appraisals,_and_requested_scheduled_limits_233",
  "estimated_dwelling_replacement_cost_234",
  "source___estimator_235",
  "estimate_date_236",
  "estimated_personal_property_value_237",
  "estimated_additional_living_expense_need_238",
  "loss_0_Date_239",
  "loss_0_Location_240",
  "loss_0_Type / Cause_241",
  "loss_0_Amount Paid_242",
  "loss_0_Status_243",
  "loss_0_Claim Number_244",
  "loss_1_Date_245",
  "loss_1_Location_246",
  "loss_1_Type / Cause_247",
  "loss_1_Amount Paid_248",
  "loss_1_Status_249",
  "loss_1_Claim Number_250",
  "loss_2_Date_251",
  "loss_2_Location_252",
  "loss_2_Type / Cause_253",
  "loss_2_Amount Paid_254",
  "loss_2_Status_255",
  "loss_2_Claim Number_256",
  "loss_3_Date_257",
  "loss_3_Location_258",
  "loss_3_Type / Cause_259",
  "loss_3_Amount Paid_260",
  "loss_3_Status_261",
  "loss_3_Claim Number_262",
  "mortgage_company___lender_263",
  "loan_number_264",
  "mortgagee_mailing_address_265",
  "city_266",
  "state_267",
  "zip_268",
  "second_mortgage___heloc_lender_269",
  "loan_number_270",
  "additional_underwriting_remarks_271",
  "prior_declarations_attached_272",
  "loss_runs_attached_273",
  "inspection_attached_274",
  "photos_attached_275",
  "applicant_signature_276",
  "date_277",
  "producer___agency_278",
  "co-applicant_signature_279",
  "date_280",
  "producer_phone_281",
];

export const HA_FORM_NAME = "homeowners-application";
